### PR TITLE
Add more types and functions

### PR DESCRIPTION
**Pull request by 5ohue**
Oof. I believe after this pull request there's almost no `bindings` in the public library api. Most of the types are wrapped in enums and `size_t` is replaced with `usize`.

This pull request also adds a few new methods to `MagickWand`.

### CODE REVIEW

**Comment by 5ohue** [comment]
Ok, I probably opened this too early, I keep adding more stuff that I need. I'll add a comment here when this should be merged

**Comment by nlfiedler** [comment]
No problem at all, keep 'em coming. Thanks.

**Comment by 5ohue** [comment]
I think this is good to be merged

**Comment by nlfiedler** [comment]
Thank you again, sorry for the delay.

**Pull request merged**
