### PR TITLE
Update bindgen to 0.51

### PR DESCRIPTION
**Pull request by davidarmstronglewis**
Thanks for maintaining this crate :)

### CODE REVIEW

**Comment by nlfiedler** [comment]
Have you seen issue #10 with regards to this? In particular, does this change work for you on Linux? When I tried doing it myself using the docker container it fails to compile with an outrageously-hugely-enormous error message (because it prints the line of code that has the error, which is apparently the _entire_ input file). Maybe you had better luck?

**Comment by davidarmstronglewis** [comment]
Ooh, I have not tried this on Linux yet. I'll do that tomorrow and see if it build *fingers crossed*.

**Comment by davidarmstronglewis** [comment]
Okay, finally got around to trying this on Linux, ended up with a nice large error ending with...
```
error: aborting due to 12 previous errors

Some errors have detailed explanations: E0277, E0428.
For more information about an error, try `rustc --explain E0277`.
The following warnings were emitted during compilation:

warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

error: Could not compile `magick_rust`.

To learn more, run the command again with --verbose.
```

This definitely doesn't happen on the previous version of `bindgen` 🤷‍♀

**Comment by davidarmstronglewis** [comment]
Okay, so this seems to be an issue I don't have when building for musl. Do you have any continuous integration testing set up for this project?

**Comment by nlfiedler** [comment]
To test for Linux, I use the docker container that's defined in the repo; see the README for instructions. If the crate compiles on that, and macOS, then I'm completely satisfied.

**Comment by davidarmstronglewis** [comment]
Okay, yep. That asplodes. Interesting that it doesn't on other platforms.

**Pull request closed without merging**
